### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by AdrisGithub** [Uzade/BobbyBot#14]
Ein kleines Icon auf dem Bildschirm steht,
ein Häschen, das sich vor uns dreht,
sein pelziger Anblick erfreut,
und uns auf eine Webseite bezieht.

Ein Symbol für Liebe und Zärtlichkeit,
für einzigartige Inhalte bereit,
mit jedem Klick auf den Hasen,
öffnen sich neue Wege und Straßen.

Denn das Icon ist mehr als nur ein Tier,
es steht für die Website und ihre Gier,
uns mit Freude und Wissen zu beschenken,
unsere Sinne zu erwecken.

So lass uns zusammen das Icon verehren,
und seine Bedeutung niemals entehren,
denn es ist der Schlüssel zur Tür,
in eine Welt voller Spaß und Pläsier.
Danke...
@Exubitor @Uzade

**Comment by AdrisGithub** [comment]
wann icon ?

**Comment by AdrisGithub** [comment]
Pläsier n. (auch Plaisier, bis gegen 1900) 'Vergnügen, Spaß, Unterhaltung', Übernahme (um 1600) von gleichbed. afrz. frz.

**Comment by Uzade** [comment]
Mach selber du Hund

**Comment by AdrisGithub** [comment]
this can be closed after the pull request is closed and merged
